name: Deploy in Github Pages
on: 
  push:
    paths:
    - 'slides/**'

permissions: 
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Install slidev
        run:  npm i -g @slidev/cli
      - name: Get talk title
        run: echo "talk_title=$(basename $(git show ${{ github.sha }} --name-only -- "slides/" | grep "slides/" | tail -n 1) .md)" >> "$GITHUB_ENV"
      - name: Debug
        run: echo ${{env.talk_title}}
      - name: Build
        run: slidev build --base /lectures/${{env.talk_title}} slides/${{env.talk_title}}/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: slides/${{env.talk_title}}/dist # The folder the action should deploy.
          target-folder: ${{ env.talk_title }}
          clean: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}